import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { CSS2DRenderer, CSS2DObject } from "three/addons/renderers/CSS2DRenderer.js";
import { EffectComposer } from "three/addons/postprocessing/EffectComposer.js";
import { RenderPass } from "three/addons/postprocessing/RenderPass.js";
import { UnrealBloomPass } from "three/addons/postprocessing/UnrealBloomPass.js";
import { OutputPass } from "three/addons/postprocessing/OutputPass.js";

/* =========================================================================
   GritShield — feature module catalogue
   ========================================================================= */
const MODULES = [
  {
    id: "security",
    name: "Security",
    icon: "🔒",
    cat: "SECURITY CORE",
    color: 0x00e0ff,
    tagline: "OWASP Top 10 eliminated by design.",
    desc: "A dual-layer RBAC + capability model with compile-time structural verification, signed & secure cookies, CSRF protection, XSS-safe sanitization, per-IP rate limiting and IP blacklisting — secure by default from the very first byte.",
    file: "src/main.rs",
    code: `// Declare a single source of truth for access boundaries
declare_security_caps! {
    ManageBilling => [Admin, Manager, Operator],
    DeleteUser    => [Admin],
}

#[controller("/api/billing")]
impl BillingController {
    #[get("/audit-logs")]
    #[cap(ViewLogs)]              // verified at compile time
    pub async fn get_audit_logs(&self) -> Response {
        Response::ok("Logs retrieved securely.")
    }
}`,
  },
  {
    id: "macros",
    name: "Macro Library",
    icon: "🧩",
    cat: "COMPILE-TIME MAGIC",
    color: 0xa06bff,
    tagline: "Spring-Boot patterns, generated by the compiler.",
    desc: "Every framework annotation is a procedural macro expanding at compile time. No runtime reflection, no interpreter — the exact code you'd hand-write is generated for you, checked by the type system.",
    file: "src/main.rs",
    code: `#[get("/api/users/:id")]
async fn get_user(ctx: RequestContext) -> Response {
    let id = ctx.params.get("*id")?.as_str();
    Response::ok(format!("User {id}"))
}

// @Transactional, @ExceptionHandler, @Autowired...
#[transactional]
#[intercept(AuditLogger)]
pub async fn create_user(&self, id: i64, email: String) -> Result<(), DbErr> {
    // BEGIN / COMMIT / ROLLBACK handled for you
}`,
  },
  {
    id: "di",
    name: "Dependency Injection",
    icon: "🏗️",
    cat: "DUAL-ENGINE IOC",
    color: 0x34f5c5,
    tagline: "Dynamic inventory magic, or zero-overhead compile-time wiring.",
    desc: "Pick Paradigm A (auto-discovery, Spring-style) or Paradigm B (WireContainer — a missing dependency is a hard compiler error). Either way, dependencies resolve at compile time with zero runtime cost.",
    file: "src/main.rs",
    code: `#[derive(GritComponent)]
pub struct OrderController {
    pub db: Arc<DatabasePool>,
    pub ps: Arc<PaymentService>,   // auto-injected
}

#[controller("/api/orders")]
impl OrderController {
    #[post("/checkout")]
    pub async fn checkout(
        ctx: RequestContext,
        payment_service: Arc<PaymentService>,
    ) -> Response {
        // wired automatically
        Result
    }
}`,
  },
  {
    id: "routing",
    name: "Routing",
    icon: "🗺️",
    cat: "TRIE-BASED",
    color: 0xffc757,
    tagline: "O(n) trie matching. Static, dynamic & wildcard routes.",
    desc: "A prefix-tree router resolves paths in O(n) where n is the number of segments. Exact matches, :params and /** wildcards with a clean precedence order, plus named role-guarded routes.",
    file: "src/router.rs",
    code: `#[get("/users/:id")]
async fn user(ctx: RequestContext) -> String {
    format!("User: {}", ctx.params.get("id")?.as_str())
}

#[get("/static/:*path")]            // wildcard
async fn static_files(ctx: RequestContext) -> Response {
    Response::static_file(&format!("static/{path}"))
}`,
  },
  {
    id: "admin",
    name: "GritAdmin",
    icon: "📊",
    cat: "AUTO-GENERATED UI",
    color: 0xff5fae,
    tagline: "A full CRUD admin panel from one derive.",
    desc: "Annotate your repository with #[derive(GritAdmin)] and get a complete admin interface — inline editing, advanced filters, infinite scroll and a browser-based JQL query explorer with JOIN support. Zero frontend code.",
    file: "src/repositories/user_repo.rs",
    code: `#[derive(GritAdmin)]
#[repository(
    searchable = ["email", "username"],
    grid_columns = ["id", "email", "username", "status"],
    read_only   = ["id", "created_at"],
)]
pub struct UserRepository {
    pub db: sea_orm::DatabaseConnection,
}
// → /admin/dashboard, /admin/docs (Swagger)`,
  },
  {
    id: "events",
    name: "Event Bus & Jobs",
    icon: "⚡",
    cat: "ASYNC WORKLOADS",
    color: 0xff9f43,
    tagline: "Pub/Sub events + a resilient, retrying job queue.",
    desc: "Fire-and-forget domain events via an in-process bus, or defer heavy work to a persistent job queue with exponential-backoff retries, delayed scheduling and cron. Both are transaction-aware — dispatched only after a successful commit.",
    file: "src/jobs/compress.rs",
    code: `#[derive(GritEvent)]
pub struct UserRegisteredEvent { pub user_id: String }

#[derive(GritJob)]
#[job(name = "compress_image", retries = 5)]
pub struct CompressImageJob { pub url: String }

// fire & forget
ctx.event_bus.publish(UserRegisteredEvent { user_id });
// deferred heavy work
CompressImageJob { url }.enqueue().await;`,
  },
  {
    id: "websocket",
    name: "WebSocket",
    icon: "🔌",
    cat: "REALTIME",
    color: 0x4fe3c1,
    tagline: "Real-time routing with one macro.",
    desc: "Register WebSocket endpoints with register_ws! and handle streams directly with tokio-tungstenite. Full-duplex messaging, built on async Rust.",
    file: "src/main.rs",
    code: `async fn echo_handler(
    mut stream: WebSocketStream<TcpStream>,
    ctx: RequestContext,
) {
    while let Some(msg) = stream.next().await {
        if let Ok(m) = msg {
            let _ = stream.send(m).await;   // echo
        }
    }
}

register_ws!("/ws/echo", echo_handler);`,
  },
  {
    id: "database",
    name: "Database & ORM",
    icon: "🗄️",
    cat: "TYPE-SAFE DATA",
    color: 0x6fd1ff,
    tagline: "SeaORM integration, migrations & rich query DSL.",
    desc: "Write query-by-method DSL that compiles into efficient SQL: find_by_field, chained AND/OR, range, LIKE, eager relation loading and deep nested loads — all generated from your models at compile time.",
    file: "src/models/user.rs",
    code: `#[derive(GritModel)]
#[sea_orm(table_name = "users")]
pub struct User { /* ... */ }

let active_premium = user_repo
    .find_by_status_and_tier("active", "premium")
    .await?;

let user_deep = user_repo
    .find_by_id(1)
    .with_posts_nested(|q| q.with_comments())
    .await?;`,
  },
];

const COLORS = {
  cyan: 0x00e0ff,
  violet: 0xa06bff,
  emerald: 0x34f5c5,
  amber: 0xffc757,
  pink: 0xff5fae,
  orange: 0xff9f43,
  mint: 0x4fe3c1,
  sky: 0x6fd1ff,
};

/* =========================================================================
   Renderers / scene setup
   ========================================================================= */
const container = document.getElementById("webgl");

const scene = new THREE.Scene();
scene.fog = new THREE.FogExp2(0x04070f, 0.0016);

const camera = new THREE.PerspectiveCamera(50, innerWidth / innerHeight, 0.1, 600);
camera.position.set(0, 2.2, 15);

const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true, powerPreference: "high-performance" });
renderer.setSize(innerWidth, innerHeight);
renderer.setPixelRatio(Math.min(devicePixelRatio, 2));
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1.1;
container.appendChild(renderer.domElement);

const labelRenderer = new CSS2DRenderer();
labelRenderer.setSize(innerWidth, innerHeight);
labelRenderer.domElement.style.position = "fixed";
labelRenderer.domElement.style.inset = "0";
labelRenderer.domElement.style.pointerEvents = "none";
labelRenderer.domElement.style.zIndex = "2";
container.appendChild(labelRenderer.domElement);

const composer = new EffectComposer(renderer);
composer.addPass(new RenderPass(scene, camera));
const bloom = new UnrealBloomPass(new THREE.Vector2(innerWidth, innerHeight), 1.35, 0.5, 0.78);
composer.addPass(bloom);
composer.addPass(new OutputPass());

const controls = new OrbitControls(camera, renderer.domElement);
controls.enableDamping = true;
controls.dampingFactor = 0.06;
controls.autoRotate = true;
controls.autoRotateSpeed = 0.6;
controls.minDistance = 7;
controls.maxDistance = 34;
controls.maxPolarAngle = Math.PI * 0.82;
controls.enablePan = false;
controls.target.set(0, 0, 0);

/* =========================================================================
   Lighting
   ========================================================================= */
scene.add(new THREE.AmbientLight(0x223252, 1.2));
const key = new THREE.DirectionalLight(0x9fc4ff, 1.4);
key.position.set(6, 8, 6);
scene.add(key);
const rim = new THREE.PointLight(0x00e0ff, 2.2, 40);
rim.position.set(-6, -2, -4);
scene.add(rim);

/* =========================================================================
   Starfield backdrop
   ========================================================================= */
function makeStars() {
  const count = 3600;
  const pos = new Float32Array(count * 3);
  const col = new Float32Array(count * 3);
  for (let i = 0; i < count; i++) {
    const r = 80 + Math.random() * 220;
    const theta = Math.random() * Math.PI * 2;
    const phi = Math.acos(2 * Math.random() - 1);
    pos[i * 3] = r * Math.sin(phi) * Math.cos(theta);
    pos[i * 3 + 1] = r * Math.sin(phi) * Math.sin(theta);
    pos[i * 3 + 2] = r * Math.cos(phi);
    const tint = Math.random();
    const b = 0.55 + Math.random() * 0.45;
    col[i * 3] = tint < 0.8 ? b : 0.7 * b;        // mostly white -> slight cyan
    col[i * 3 + 1] = tint < 0.8 ? b * 0.9 : b;
    col[i * 3 + 2] = tint < 0.8 ? b : 1.0 * b;
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.BufferAttribute(pos, 3));
  g.setAttribute("color", new THREE.BufferAttribute(col, 3));
  const m = new THREE.PointsMaterial({ size: 0.22, vertexColors: true, transparent: true, opacity: 0.9, depthWrite: false });
  const pts = new THREE.Points(g, m);
  pts.frustumCulled = false;
  return pts;
}
const stars = makeStars();
scene.add(stars);

/* =========================================================================
   Central shield core — hexagon prism wireframe + particle lattice + glow
   ========================================================================= */
const shieldGroup = new THREE.Group();
scene.add(shieldGroup);

function hexagonPrismLines(radius, height, ySegs) {
  const points = [];
  // top & bottom hexagon rings
  function ring(y) {
    const ring = [];
    for (let i = 0; i < 6; i++) {
      const a = (i / 6) * Math.PI * 2 + Math.PI / 6;
      ring.push(new THREE.Vector3(Math.cos(a) * radius, y, Math.sin(a) * radius));
    }
    return ring;
  }
  const top = ring(height / 2);
  const bot = ring(-height / 2).map((v) => v.clone());
  const innerTop = ring(height / 2 - 0.12);
  const innerBot = ring(-height / 2 + 0.12);

  // vertical slices
  const ys = [];
  for (let i = 0; i <= ySegs; i++) ys.push(-height / 2 + (height * i) / ySegs);

  // build edges: hexagon sides top & bottom, verticals, and inner shell
  for (const [arr, colorHex] of [
    [top, 0x4fd8ff],
    [bot, 0x4fd8ff],
  ]) {
    for (let i = 0; i < 6; i++) {
      points.push(seg(arr[i], arr[(i + 1) % 6], colorHex));
    }
  }
  for (let i = 0; i < 6; i++) {
    points.push(seg(top[i], bot[i], 0x2f7fbb));
    points.push(seg(innerTop[i], innerBot[i], 0x2f7fbb));
  }
  for (let i = 0; i < 6; i++) {
    points.push(seg(top[i], innerTop[i], 0x2f7fbb));
    points.push(seg(bot[i], innerBot[i], 0x2f7fbb));
    points.push(seg(top[i], innerTop[(i + 1) % 6], 0x2f7fbb));
    points.push(seg(bot[i], innerBot[(i + 1) % 6], 0x2f7fbb));
  }
  return points;
}
function seg(a, b, colorHex) {
  const c = new THREE.Color(colorHex);
  return { a, b, color: c };
}

// Hexagon prism (wireframe edges, vertex-colored)
{
  const segs = hexagonPrismLines(2.6, 4.6, 3);
  const positions = new Float32Array(segs.length * 2 * 3);
  const colors = new Float32Array(segs.length * 2 * 3);
  segs.forEach((s, i) => {
    positions.set([s.a.x, s.a.y, s.a.z], i * 6);
    positions.set([s.b.x, s.b.y, s.b.z], i * 6 + 3);
    colors.set([s.color.r, s.color.g, s.color.b], i * 6);
    colors.set([s.color.r, s.color.g, s.color.b], i * 6 + 3);
  });
  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.BufferAttribute(positions, 3));
  g.setAttribute("color", new THREE.BufferAttribute(colors, 3));
  const m = new THREE.LineBasicMaterial({ vertexColors: true, transparent: true, opacity: 0.55 });
  shieldGroup.add(new THREE.LineSegments(g, m));

  // translucent core
  const core = new THREE.CylinderGeometry(2.5, 2.5, 4.4, 6, 1);
  const coreMat = new THREE.MeshBasicMaterial({
    color: 0x0a2a44, transparent: true, opacity: 0.28, side: THREE.DoubleSide,
  });
  const coreMesh = new THREE.Mesh(core, coreMat);
  coreMesh.geometry.translate(0, 0, 0);
  coreMesh.rotation.y = Math.PI / 6;
  shieldGroup.add(coreMesh);
}

// Particle lattice filling the core
{
  const count = 2600;
  const pos = new Float32Array(count * 3);
  const col = new Float32Array(count * 3);
  const colCyan = new THREE.Color(0x53e6ff);
  const colViolet = new THREE.Color(0x8f7bff);
  const colWhite = new THREE.Color(0xdff5ff);
  for (let i = 0; i < count; i++) {
    // point in a filled hexagon cylinder
    const r = Math.cbrt(Math.random()) * 2.5;
    const a = Math.random() * Math.PI * 2;
    const y = (Math.random() * 2 - 1) * 4.2;
    pos[i * 3] = Math.cos(a) * r;
    pos[i * 3 + 1] = y;
    pos[i * 3 + 2] = Math.sin(a) * r;
    const t = Math.random();
    const c = t < 0.15 ? colWhite : t < 0.5 ? colCyan : colViolet;
    const fade = 0.55 + Math.random() * 0.45;
    col[i * 3] = c.r * fade;
    col[i * 3 + 1] = c.g * fade;
    col[i * 3 + 2] = c.b * fade;
  }
  const g = new THREE.BufferGeometry();
  g.setAttribute("position", new THREE.BufferAttribute(pos, 3));
  g.setAttribute("color", new THREE.BufferAttribute(col, 3));
  const m = new THREE.PointsMaterial({ size: 0.09, vertexColors: true, transparent: true, depthWrite: false, opacity: 0.9 });
  const p = new THREE.Points(g, m);
  shieldGroup.add(p);
}

// Center glow sprite
{
  const sprite = document.createElement("canvas");
  sprite.width = sprite.height = 256;
  const c = sprite.getContext("2d");
  const grad = c.createRadialGradient(128, 128, 0, 128, 128, 128);
  grad.addColorStop(0, "rgba(80,220,255,0.55)");
  grad.addColorStop(0.35, "rgba(40,120,220,0.18)");
  grad.addColorStop(1, "rgba(0,0,0,0)");
  c.fillStyle = grad;
  c.fillRect(0, 0, 256, 256);
  const tex = new THREE.CanvasTexture(sprite);
  const sp = new THREE.Sprite(new THREE.SpriteMaterial({ map: tex, blending: THREE.AdditiveBlending, depthWrite: false, transparent: true }));
  sp.scale.set(13, 13, 1);
  shieldGroup.add(sp);
}

/* =========================================================================
   Orbiting feature modules
   ========================================================================= */
function buildNodeMesh(cfg, radius) {
  let geo;
  switch (cfg.id) {
    case "security": geo = new THREE.IcosahedronGeometry(0.62, 0); break;
    case "macros": geo = new THREE.TetrahedronGeometry(0.7, 0); break;
    case "di": geo = new THREE.OctahedronGeometry(0.66, 0); break;
    case "routing": geo = new THREE.TorusGeometry(0.42, 0.17, 12, 24); break;
    case "admin": geo = new THREE.BoxGeometry(0.9, 0.9, 0.9); break;
    case "events": geo = new THREE.TorusKnotGeometry(0.42, 0.15, 90, 12); break;
    case "websocket": geo = new THREE.CylinderGeometry(0.34, 0.34, 0.9, 24); break;
    case "database": geo = new THREE.CylinderGeometry(0.62, 0.62, 0.55, 12); break;
    default: geo = new THREE.SphereGeometry(0.6, 24, 20);
  }
  const color = new THREE.Color(cfg.color);
  const coreMat = new THREE.MeshStandardMaterial({
    color, roughness: 0.25, metalness: 0.6, emissive: color, emissiveIntensity: 0.55,
  });
  const mesh = new THREE.Mesh(geo, coreMat);
  // wireframe shell
  const wire = new THREE.LineSegments(
    new THREE.EdgesGeometry(geo),
    new THREE.LineBasicMaterial({ color, transparent: true, opacity: 0.75 })
  );
  wire.scale.setScalar(1.32);
  mesh.add(wire);
  return mesh;
}

const nodes = [];
const nodeRadius = 7.5;
const nodeCount = MODULES.length;

// Tilted elliptical orbit rings
for (let i = 0; i < nodeCount; i++) {
  const cfg = MODULES[i];
  const angle = (i / nodeCount) * Math.PI * 2;
  const tiltX = Math.sin(i * 1.7) * 0.35;
  const tiltZ = Math.cos(i * 1.3) * 0.28;
  const x = Math.cos(angle) * nodeRadius;
  const z = Math.sin(angle) * nodeRadius * 0.82;
  const y = Math.sin(angle * 1.3) * 1.6;

  const holder = new THREE.Group();
  holder.rotation.x = -0.18 + tiltX;
  holder.rotation.z = -0.1 + tiltZ;

  const mesh = buildNodeMesh(cfg, nodeRadius);
  mesh.position.set(x, y, z);
  holder.add(mesh);

  // point light at each node
  const light = new THREE.PointLight(cfg.color, 1.4, 8);
  light.position.set(x, y, z);
  holder.add(light);

  // CSS2D label
  const labelDiv = document.createElement("div");
  labelDiv.className = "node-label";
  labelDiv.textContent = cfg.icon + "  " + cfg.name;
  labelDiv.style.borderColor = "rgba(" + (cfg.color >> 16) + "," + ((cfg.color >> 8) & 255) + "," + (cfg.color & 255) + ",0.5)";
  const label = new CSS2DObject(labelDiv);
  label.position.set(x, y + 1.35, z);
  holder.add(label);

  holder.userData = { cfg, mesh, basePos: new THREE.Vector3(x, y, z), angle, label: labelDiv };
  shieldGroup.add(holder);
  nodes.push(holder);
}

// Connected ring (lines between adjacent nodes + node->core)
{
  const pts = nodes.map((n) => n.userData.basePos);
  const ringPos = [];
  for (let i = 0; i < pts.length; i++) {
    const a = pts[i], b = pts[(i + 1) % pts.length];
    ringPos.push(a.x, a.y, a.z, b.x, b.y, b.z);
  }
  const rg = new THREE.BufferGeometry();
  rg.setAttribute("position", new THREE.BufferAttribute(new Float32Array(ringPos), 3));
  const ringMat = new THREE.LineBasicMaterial({ color: 0x1d3a63, transparent: true, opacity: 0.5 });
  shieldGroup.add(new THREE.LineSegments(rg, ringMat));

  // spokes: node -> origin
  for (const n of nodes) {
    const p = n.userData.basePos;
    const v = p.clone().normalize().multiplyScalar(2.6);
    const geo = new THREE.BufferGeometry().setFromPoints([v, p]);
    const m = new THREE.LineBasicMaterial({ color: new THREE.Color(n.userData.cfg.color).multiplyScalar(0.7), transparent: true, opacity: 0.16 });
    shieldGroup.add(new THREE.Line(geo, m));
  }
}

// Travelling energy packets along spokes
const packets = [];
{
  const geo = new THREE.SphereGeometry(0.07, 12, 12);
  for (const n of nodes) {
    const p = n.userData.basePos;
    const inner = p.clone().normalize().multiplyScalar(2.6);
    const mat = new THREE.MeshBasicMaterial({ color: n.userData.cfg.color, transparent: true, opacity: 0.95 });
    const mesh = new THREE.Mesh(geo, mat);
    shieldGroup.add(mesh);
    packets.push({ mesh, inner, outer: p.clone(), speed: 0.5 + Math.random() * 0.8, offset: Math.random() * Math.PI * 2 });
  }
}

/* =========================================================================
   Interaction — hover & click
   ========================================================================= */
const raycaster = new THREE.Raycaster();
const pointer = new THREE.Vector2();
let hovered = null;
let interacting = false;

const panel = document.getElementById("panel");
const closeBtn = document.getElementById("panel-close");
const elCat = document.getElementById("p-cat");
const elTitle = document.getElementById("p-title");
const elTag = document.getElementById("p-tagline");
const elDesc = document.getElementById("p-desc");
const elFile = document.getElementById("p-file");
const elCode = document.getElementById("p-code");

function openPanel(idx) {
  const cfg = MODULES[idx];
  elCat.textContent = cfg.cat;
  elCat.style.color = "#" + cfg.color.toString(16).padStart(6, "0");
  elTitle.textContent = cfg.icon + " " + cfg.name;
  elTag.textContent = cfg.tagline;
  elDesc.textContent = cfg.desc;
  elFile.textContent = "// " + cfg.file;
  elCode.textContent = cfg.code.trim();
  panel.classList.add("open");
  panel.setAttribute("aria-hidden", "false");
  interacting = true;
  controls.autoRotate = false;
}
function closePanel() {
  panel.classList.remove("open");
  panel.setAttribute("aria-hidden", "true");
  interacting = false;
  controls.autoRotate = true;
}
closeBtn.addEventListener("click", closePanel);
panel.addEventListener("click", (e) => { if (e.target === panel) closePanel(); });
document.addEventListener("keydown", (e) => { if (e.key === "Escape") closePanel(); });

function setPointer(e) {
  pointer.x = (e.clientX / innerWidth) * 2 - 1;
  pointer.y = -(e.clientY / innerHeight) * 2 + 1;
}
function pick(e) {
  setPointer(e);
  raycaster.setFromCamera(pointer, camera);
  const meshes = [];
  for (const n of nodes) meshes.push(n.userData.mesh);
  const hits = raycaster.intersectObjects(meshes, false);
  return hits.length ? nodes.find((n) => n.userData.mesh === hits[0].object) : null;
}
window.addEventListener("pointermove", (e) => {
  if (interacting) return;
  const hit = pick(e);
  if (hit !== hovered) {
    if (hovered) {
      hovered.userData.mesh.scale.setScalar(1);
      hovered.userData.label.classList.remove("off");
    }
    hovered = hit;
    if (hovered) {
      hovered.userData.mesh.scale.setScalar(1.35);
      hovered.userData.label.classList.add("off");
      renderer.domElement.style.cursor = "pointer";
    } else {
      renderer.domElement.style.cursor = "";
    }
  }
});
window.addEventListener("click", (e) => {
  const hit = pick(e);
  if (hit) {
    const idx = nodes.indexOf(hit);
    openPanel(idx);
  }
});

/* =========================================================================
   Feature grid cards (scroll section)
   ========================================================================= */
const grid = document.getElementById("feature-grid");
MODULES.forEach((cfg, i) => {
  const card = document.createElement("article");
  card.className = "feature-card";
  card.style.setProperty("--card-color", "#" + cfg.color.toString(16).padStart(6, "0"));
  card.style.setProperty("--card-rgb", (cfg.color >> 16) + "," + ((cfg.color >> 8) & 255) + "," + (cfg.color & 255));
  card.innerHTML =
    '<div class="fc-icon">' + cfg.icon + "</div>" +
    '<h3 class="fc-title">' + cfg.name + "</h3>" +
    '<p class="fc-desc">' + cfg.tagline + ' ' + cfg.desc.split(".")[0] + ".</p>" +
    '<div class="fc-tag">' + cfg.file + "</div>";
  card.addEventListener("click", () => openPanel(i));
  grid.appendChild(card);
});

/* =========================================================================
   Scroll / hero fade + nav buttons
   ========================================================================= */
const hero = document.getElementById("hero");
const hint = document.getElementById("hint-bar");
const body = document.body;
let decomposed = false;
function onScroll() {
  const y = window.scrollY;
  if (y > 60) body.classList.add("scrolled");
  else body.classList.remove("scrolled");
}
window.addEventListener("scroll", onScroll, { passive: true });

document.querySelectorAll("[data-scroll]").forEach((btn) => {
  btn.addEventListener("click", () => {
    const target = document.getElementById(btn.dataset.scroll);
    if (target) target.scrollIntoView({ behavior: "smooth" });
  });
});

/* =========================================================================
   Resize
   ========================================================================= */
window.addEventListener("resize", () => {
  camera.aspect = innerWidth / innerHeight;
  camera.updateProjectionMatrix();
  renderer.setSize(innerWidth, innerHeight);
  composer.setSize(innerWidth, innerHeight);
  labelRenderer.setSize(innerWidth, innerHeight);
});

/* =========================================================================
   Animation loop
   ========================================================================= */
const clock = new THREE.Clock();
function animate() {
  requestAnimationFrame(animate);
  const t = clock.getElapsedTime();

  // shield core idle motion
  shieldGroup.rotation.y = t * 0.06;
  stars.rotation.y = t * 0.004;

  // background parallax
  const camVec = camera.position.clone().normalize();
  stars.position.lerp(camVec.multiplyScalar(-2), 0.02);

  // nodes float + spin
  nodes.forEach((n, i) => {
    const cfg = n.userData;
    const m = cfg.mesh;
    m.rotation.x = t * 0.5 + i;
    m.rotation.y = t * 0.7 + i * 1.3;
    m.position.x = cfg.basePos.x + Math.sin(t * 0.8 + i * 2.1) * 0.25;
    m.position.y = cfg.basePos.y + Math.cos(t * 0.6 + i * 1.7) * 0.3;
    m.position.z = cfg.basePos.z + Math.sin(t * 0.55 + i) * 0.2;
    // label follows
    const l = n.children.find((c) => c.isCSS2DObject);
    if (l) l.position.set(m.position.x, m.position.y + 1.35, m.position.z);
  });

  // energy packets
  for (const pk of packets) {
    const k = (Math.sin(t * pk.speed + pk.offset) + 1) / 2;
    pk.mesh.position.lerpVectors(pk.inner, pk.outer, k);
    pk.mesh.material.opacity = 0.35 + 0.65 * k;
  }

  controls.update();
  composer.render();
}
animate();

// Fade labels back in if panel closed
function relabel() {
  nodes.forEach((n) => {
    if (n !== hovered) n.userData.label.classList.remove("off");
  });
}
document.addEventListener("panelchange", relabel);
