[book]
title = "GritShield Documentation"
language = "en"
src = "docs_content"
site-url = "/gritshield/"

[build]
build-dir = "book"

[output.html.playground]
editable = false
copyable = true
line-numbers = true
runnable = false
